# Sway takes configs from 3 locations:
#  - /usr/share/sway/config.d
#  - /etc/sway/config.d
#  - $HOME/.config/sway/config.d
# Reload the configuration file with $mod+Shift+c
# power button and lid controls for laptop live in /etc/systemd/logind.conf

#define lock and sleep
set $lock "swaylock -f -e -l"
set $sleep "systemctl suspend"

#screen lock bind
bindsym $mod+z exec $lock

#fast key repeat setting
input "1:1:AT_Translated_Set_2_keyboard" {
    repeat_rate 100
    repeat_delay 250
}

### Idle configuration (unsure if this is working)
exec swayidle -w \
timeout 120 $lock \
timeout 300 $sleep \
before-sleep $lock

# mod+backspace opens browser
set $browse firefox
bindsym $mod+Backspace exec $browse

# turns off mouse acceleration
# input "PIXA3854:00 093A:0274 Touchpad" {
# input "1133:50504:Logitech_USB_Receiver_Mouse" {
input "6940:7006:Corsair_CORSAIR_HARPOON_RGB_WIRELESS_Gaming_Mouse" {
    accel_profile flat
}

#display scaling and placement
output "BOE 0x095F Unknown" scale 2 pos 0 1080 
#792
output 'LG Electronics LG FULL HD 0x01010101' pos 0 0 

# removes borders
default_border pixel 2

